// Pulse — Dark Luxury Design System
// Audemars Piguet meets Whoop. Near-black surfaces, single gold accent.

export const P = {
  bg:      "#0A0A0B",
  s1:      "#111113",
  s2:      "#18181B",
  s3:      "#222226",
  border:  "#2A2A2E",
  gold:    "#C9A84C",
  goldDim: "rgba(201,168,76,0.12)",
  ink:     "#F2EEE8",
  mid:     "#6B6760",
  dim:     "#3A3A3E",
  // Functional (keep for workout logic)
  green:   "#3A7D5A",
  red:     "#B83030",
} as const;

// Legacy Colors export — mapped to Pulse tokens so useTheme() keeps working
export const Colors = {
  light: {
    background:          P.bg,
    backgroundSecondary: P.s1,
    backgroundTertiary:  P.s2,
    label:               P.ink,
    labelSecondary:      P.mid,
    labelTertiary:       P.dim,
    labelQuaternary:     P.dim,
    separator:           P.border,
    separatorOpaque:     P.border,
    fillPrimary:         P.s3,
    fillSecondary:       P.s2,
    fillTertiary:        P.s1,
    accent:              P.gold,
    accentGreen:         P.green,
    accentLight:         P.goldDim,
    accentRed:           P.red,
    accentOrange:        P.gold,
    volumeLow:           P.green,
    volumeMid:           P.gold,
    volumeHigh:          P.red,
    headerBg:            P.bg,
    repRangeBg:          P.goldDim,
    repRangeFg:          P.gold,
    loggedCheckBg:       P.green,
    setRowBg:            P.s1,
    setRowAlt:           P.s2,
  },
  dark: {
    background:          P.bg,
    backgroundSecondary: P.s1,
    backgroundTertiary:  P.s2,
    label:               P.ink,
    labelSecondary:      P.mid,
    labelTertiary:       P.dim,
    labelQuaternary:     P.dim,
    separator:           P.border,
    separatorOpaque:     P.border,
    fillPrimary:         P.s3,
    fillSecondary:       P.s2,
    fillTertiary:        P.s1,
    accent:              P.gold,
    accentGreen:         P.green,
    accentLight:         P.goldDim,
    accentRed:           P.red,
    accentOrange:        P.gold,
    volumeLow:           P.green,
    volumeMid:           P.gold,
    volumeHigh:          P.red,
    headerBg:            P.bg,
    repRangeBg:          P.goldDim,
    repRangeFg:          P.gold,
    loggedCheckBg:       P.green,
    setRowBg:            P.s1,
    setRowAlt:           P.s2,
  },
} as const;

export type ColorScheme = keyof typeof Colors;
export type ColorToken = keyof typeof Colors.light;

export const MUSCLE_BADGE_COLORS: Record<string, string> = {
  chest:      P.s2,
  back:       P.s2,
  shoulders:  P.s2,
  biceps:     P.s2,
  triceps:    P.s2,
  quads:      P.s2,
  hamstrings: P.s2,
  glutes:     P.s2,
  calves:     P.s2,
  abs:        P.s2,
  forearms:   P.s2,
};
