/**
 * Convex hooks for BaliYoLift
 *
 * useQuery, useMutation, and useConvex are re-exported directly from "convex/react".
 * API types are generated by running `npx convex dev` — they live at:
 *   convex/_generated/api.ts   (do NOT hand-edit this file)
 *
 * SETUP REQUIRED before using these hooks in screens:
 *   1. Run `npx convex dev` once to generate convex/_generated/
 *   2. Import the typed API object:
 *        import { api } from "@/convex/_generated/api";
 *   3. Then use the hooks normally:
 *        import { useQuery, useMutation } from "@/hooks/useConvex";
 *
 * Example usage in a screen:
 *
 *   import { useQuery, useMutation } from "@/hooks/useConvex";
 *   import { api } from "@/convex/_generated/api";
 *
 *   // Fetch all exercises for a muscle group (reactive — updates automatically)
 *   const exercises = useQuery(api.exercises.listByMuscleGroup, { muscleGroup: "chest" });
 *
 *   // Log a set (returns a function you call imperatively)
 *   const logSet = useMutation(api.sets.logSet);
 *   await logSet({ workoutId, exerciseId, weight: 80, reps: 10, rir: 2, ... });
 *
 *   // Seed the exercise library (run once on first launch / dev setup)
 *   const seed = useMutation(api.seed.seedExercises);
 *   await seed({});
 */

export { useQuery, useMutation, useConvex } from "convex/react";
